### ISSUE TITLE
No custom support for GooseLaTeX syntax, treating file as plain text

### ISSUE THREAD

**Issue by tdegeus** [kevinstadler/SublimeLaTeXWordCount#29]
I have a custom theme for LaTeX, that, amongst others, highlights figure environments (see https://github.com/tdegeus/GooseTheme).

LaTeXWordCount has troubles with this theme, as it gives me:

```none
No custom support for GooseLaTeX syntax, treating file as plain text
```

How should this problem be worked around (other then switching the the LaTeX highlight)? Why does LaTeXWordCount not fall back on the normal LaTeX theme?

**Comment by kevinstadler** [comment]
The basic word count function of this package simply does a word count over plain text, for specific known formats/syntax themes (i.e. LaTeX) the annotations are stripped first, then passed to the plaintext function, but the safe fallback is to treat the input as plaintext.

If you want to add support for your custom theme on your local installation, simply add the following tag just before the `wordcount_latex()` function definition in WordCount.py:
````
@custom_wordcount("GooseLaTeX")
````

Add the tag around here:
https://github.com/kevinstadler/SublimeLaTeXWordCount/blob/e78ad8ad312334673c74e04e481f3838906ab8aa/WordCount.py#L63-L67

**Comment by tdegeus** [comment]
Thanks for the workaround. I don't exactly know how the plugin works, so the following might be mute. But, isn't it possible to consider the 'scope'? I.e. my theme simply adds some rules on top of the `text.tex.latex` scope. If that scope would be used, then SublimeLaTeXWordCount would be independent on the chosen theme.
