### ISSUE TITLE
Plugin Failing After Sublime Restart

### ISSUE THREAD

**Issue by iamrecursion** [kevinstadler/SublimeLaTeXWordCount#6]
If the plugin is installed and sublime text (3) is restarted, the plugin will now fail to open via both the keyboard command and the tools menu. The fix is to reinstall the plugin, but (as you can imagine) this is somewhat annoying!

**Comment by kevinstadler** [comment]
I'm assuming that this was fixed by 947f8ce, but please leave a comment here if you're still affected
